---
collections:
  - redhat.satellite
  - redhat.rhel_idm
  - ansible.netcommon
  - ansible.posix
  - ansible.utils
  - ansible.windows
  - ansible.controller
  - community.general
  - community.windows
  - community.postgresql
  - community.vmware
  - community.crypto

  
