---
collections:
  - name: redhat.satellite
  - name: redhat.rhel_idm
  - name: ansible.netcommon
  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.windows
  - name: ansible.controller
