---
collections:
  - name: redhat.satellite
  - name: redhat.rhel_idm
  - name: ansible.netcommon
  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.windows
  - name: ansible.controller
  - name: community.general
  - name: community.windows
  - name: community.postgresql
  - name: community.vmware
  - name: community.crypto

  
